<a href="https://colab.research.google.com/github/deftydev/Crew_Agents/blob/main/RNN_%26_LSTM_DEMO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
input= [1,2,3,4]
output=[2,4,6,8]

In [2]:
w = 0.0
b = 0.0
lr = 0.01

In [3]:
for epoch in range(100):
  total_loss=0
  for x,y in zip(input,output):
    y_pred=w*x+b
    error=y_pred-y
    loss = error**2
    total_loss = total_loss + loss

    dw= 2*error*x
    db= 2*error

    w= w-lr*dw
    b= b-lr*db

  if epoch%10==0:
    print(f"epoch:{epoch},   Loss:{total_loss},  w:{w},    b:{b}")
    print(" ")

test_data = 7
prediction = w*test_data + b
print(prediction)

epoch:0,   Loss:79.87961196262401,  w:0.97096256,    b:0.33802464
 
epoch:10,   Loss:0.23167004612544786,  w:1.8256613181208952,    b:0.5596735903428669
 
epoch:20,   Loss:0.1802532439422414,  w:1.8466864144525723,    b:0.4933350597409343
 
epoch:30,   Loss:0.13998891501896488,  w:1.8648906985264255,    b:0.4347575191083777
 
epoch:40,   Loss:0.10871858414000884,  w:1.880933299619277,    b:0.3831353040251137
 
epoch:50,   Loss:0.08443333195409766,  w:1.8950710351359283,    b:0.33764260473919433
 
epoch:60,   Loss:0.06557285124030263,  w:1.9075300849671393,    b:0.29755161515366857
 
epoch:70,   Loss:0.05092537177284956,  w:1.9185097728042844,    b:0.2622209473503665
 
epoch:80,   Loss:0.03954980515791557,  w:1.9281857550528785,    b:0.23108537049551264
 
epoch:90,   Loss:0.03071528068574688,  w:1.9367128310375321,    b:0.2036467681039125
 
13.786374872617987


In [8]:
import tensorflow as tf
import numpy as np

In [8]:
x = np.array(input,dtype=float)
y = np.array(output, dtype=float)

Simple RNN

In [9]:
model = tf.keras.Sequential([tf.keras.layers.Dense(20,activation='relu',input_shape = [1]),
                    tf.keras.layers.Dense(1) ])

In [10]:
model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=.01),loss='mean_squared_error')

In [11]:
model.fit(x,y,epochs=1000,verbose=1)
model.save("euron_gen_ai_first.h5")

Epoch 1/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 391ms/step - loss: 8.0777
Epoch 2/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 2.1955
Epoch 3/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.3900
Epoch 4/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 0.0555
Epoch 5/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0144
Epoch 6/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 0.0102
Epoch 7/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0096
Epoch 8/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 0.0094
Epoch 9/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0093
Epoch 10/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.0091
Epoch 11/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0089
Epoch 12/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0088
Epoch 13/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 0.0086
Epoch 14/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0085
Epoch 15/1000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.0083
Ep

In [12]:
import numpy as np
test_data = np.array([19])
model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step


array([[37.97622]], dtype=float32)

LSTM

In [14]:
data='need'

In [15]:
char2idx = {'n':0 , 'e' : 1 , "e":2 , "d" :3}
idx2char = {v : k for k , v in char2idx.items()}

In [16]:
input_seq = [char2idx[c] for c in data[:-1]]
target_seq = [char2idx[c] for c in data [1:]]

In [17]:
input_seq

[0, 2, 2]

In [18]:
x = tf.one_hot(input_seq,depth=4 )
x = tf.expand_dims(x , axis=0)
y = tf.expand_dims(target_seq , axis=0)

In [19]:
x

<tf.Tensor: shape=(1, 3, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]]], dtype=float32)>

In [24]:
model = tf.keras.Sequential([tf.keras.layers.LSTM(8,return_sequences=True , input_shape =(3,4) ) ,
                     tf.keras.layers.Dense(4,activation='linear')])

In [25]:
model.compile(optimizer='adam' ,loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))

In [27]:
for epoch in range(201):
    model.train_on_batch(x,y)

    if epoch % 50  == 0 :
        output = model(x)
        print(output)
        pred = tf.argmax(output,axis = -1).numpy()[0]
        pred_char = "".join([idx2char[i] for i in pred] )
        current_loss = model.evaluate(x, y, verbose=0)
        print(f"epoch : {epoch} , prediction : {pred_char} , loss : {current_loss} ")

tf.Tensor(
[[[-0.0851712   0.00060334  0.02300444 -0.02316779]
  [-0.007378    0.01974663 -0.01709936  0.03697261]
  [ 0.05588349  0.04141303 -0.05887519  0.08530229]]], shape=(1, 3, 4), dtype=float32)
epoch : 0 , prediction : edd , loss : 1.362656593322754 
tf.Tensor(
[[[-0.1708792  -0.09459455  0.13174859  0.03277541]
  [-0.12710732 -0.12686172  0.13552439  0.13967444]
  [-0.07402986 -0.13314906  0.10789002  0.23342018]]], shape=(1, 3, 4), dtype=float32)
epoch : 50 , prediction : edd , loss : 1.2326558828353882 
tf.Tensor(
[[[-0.28080198 -0.20896712  0.2561284   0.08462112]
  [-0.28849453 -0.31862354  0.32560006  0.28359768]
  [-0.26285997 -0.38020998  0.32206157  0.48841313]]], shape=(1, 3, 4), dtype=float32)
epoch : 100 , prediction : eed , loss : 1.07698655128479 
tf.Tensor(
[[[-0.43610764 -0.36473295  0.41934487  0.12651145]
  [-0.5638824  -0.6065409   0.5856396   0.50831246]
  [-0.63592863 -0.76442593  0.60739106  0.96557057]]], shape=(1, 3, 4), dtype=float32)
epoch : 150 , pred

In [28]:
model.save('euron_lstm.h5')